---
name: Test E2E
description: Run e2e tests
inputs:
  working_directory:
    description: 'Working directory'
    required: false
    default: .
runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: neptune-ai/kedro-neptune
          path: ${{ inputs.working_directory }}

      - name: Install development packages
        working-directory: ${{ inputs.working_directory }}
        run: pip install -e .[dev]
        shell: bash

      - name: List dependencies
        run: |
          pip list
        shell: bash

      - name: Test standard
        working-directory: ${{ inputs.working_directory }}/examples/planets
        run: export PYTHONPATH=$PWD/src; pytest ../../tests/kedro_neptune/test_utils.py
        shell: bash

#      - name: Test parallel run
#        working-directory: ${{ inputs.working_directory }}/examples/planets
#        run: export PYTHONPATH=$PWD/src; pytest ../../tests -m parallel
#        shell: bash
