---
name: Test E2E
description: Run e2e tests
inputs:
  working_directory:
    description: 'Working directory'
    required: false
    default: $PWD
runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: neptune-ai/kedro-neptune
          path: ${{ inputs.working_directory }}

      - name: Install development packages
        working-directory: ${{ inputs.working_directory }}
        run: pip install -e .[dev]
        shell: bash

      - name: Lint
        working-directory: ${{ inputs.working_directory }}
        run: python -m pylint -j 0 -f parseable kedro_neptune tests
        shell: bash

      - name: Build and test
        working-directory: ${{ inputs.working_directory }}/examples/planets
        run: export PYTHONPATH=$PWD/src; py.test ${{ inputs.working_directory }}/tests
        shell: bash
