name: kedro-neptune
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] #, ubuntu-latest]
        python-version: [3.7] #, 3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.E2E_NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: e2e-tests/integrations
        uses: ./.github/actions/e2e
#
#  publish:
#    needs: test
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#
#      - name: Install build dependencies
#        run: pip install poetry poetry-dynamic-versioning
#
#      - name: Build package
#        run : |
#          poetry build
#
#      - name: Publish package
#        uses: pypa/gh-action-pypi-publish@v1.5.1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
