name: kedro-neptune
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Windows builds fail because of the file header check - not clear what causes this.
        # There are no pylint-file-header issues about this, and Windows builds succeed in the old domain
        os: [ubuntu-latest]
        python-version: [3.6] #, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install development packages
        run: |
          pip install -e .[dev]
      - name: Lint
        run : |
          python -m pylint -j 0 -f parseable kedro_neptune tests
      - name: Build and test
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.E2E_NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{ secrets.E2E_NEPTUNE_PROJECT }}
        run: |
          cd examples/planets; export PYTHONPATH=$PWD/src; py.test $GITHUB_WORKSPACE/tests

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build and test
        run : |
          python setup.py sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
